return {
	MOD_NAME = "Where Is It",
	ENTITY_INPUT_PLACEHOLDER = "Code Name",
	ENTITY_INPUT_CUSTOM_PLACEHOLDER = "Custom Name",
	FAILED_TO_FIND = "Failed To Find",
	NO_ENTITY_SELECTED = "No Entity Selected",
	PINNED = "Pinned",
	UNPINNED = "Unpinned",
	INTERACTION_HELPER = "Shift + Right Click = Teleport || CTRL + Right Click = Toggle Favourite || ALT + Right Click = Remove/Hide",
	ADD_ENTITY = "Add Entity",
	SETTINGS = "Settings",
	SETTINGS_BASE_DESCRIPTION = "All settings are saved across servers, remember to press save to apply your new settings",
	MENU_KEY = "Menu Key",
	MENU_KEY_DESCRIPTION = "Toggle the Where Is It mod menu",
	REPEAT_KEY = "Repeat Key",
	REPEAT_KEY_DESCRIPTION = "Hotkey to quickly repeat your last entity search",
	MENU_BUTTON_TOGGLE = "Menu Button Toggle",
	MENU_BUTTON_TOGGLE_DESCRIPTION = "Toggle between show or hide main hud menu button",
	SAVE = "Save",
	RESET = "Reset",
	BACK = "Back",
	ENTITY_ON_COOLDOWN = "Entity lookup on cooldown",
	TELEPORTED_TO = "Teleported to ",
	TELEPORT_PERMISSION_OFF = "Teleport permission is not enabled",
	DEFAULT = "Default",
	FAVOURITE = "Favourites",
	HIDDEN = "Hidden",
	CUSTOM = "Custom",
}
