return {
	MOD_NAME = "在哪里",
	ENTITY_INPUT_PLACEHOLDER = "代码名称",
	FAILED_TO_FIND = "未能找到",
	NO_ENTITY_SELECTED = "未选择实体",
	PINNED = "已置顶",
	UNPINNED = "已取消置顶",
	INTERACTION_HELPER = "Shift + 右键 = 传送 || Ctrl + 右键 = 切换置顶 || Alt + 右键 = 删除",
	ADD_ENTITY = "添加实体",
	SETTINGS = "设置",
	SETTINGS_BASE_DESCRIPTION = "所有设置会在服务器间保存，请记得点击保存以应用新的设置",
	MENU_KEY = "菜单键",
	MENU_KEY_DESCRIPTION = "开关「在哪里」模组菜单",
	REPEAT_KEY = "重复键",
	REPEAT_KEY_DESCRIPTION = "快速重复上一次实体搜索",
	MENU_BUTTON_TOGGLE = "菜单按钮",
	MENU_BUTTON_TOGGLE_DESCRIPTION = "切换显示或隐藏主HUD菜单按钮",
	SAVE = "保存",
	RESET = "重置",
	BACK = "返回",
	ENTITY_ON_COOLDOWN = "实体定位正在冷却中",
	TELEPORTED_TO = "传送至 ",
	TELEPORT_PERMISSION_OFF = "传送权限未开启",
}
