-- REMEMBER TO COMPLETE THIS ENTITY LIST PRIOR TO RELEASE

return {
    {name="multiplayer_portal", icon_atlas="images/scrapbook_icons2.xml", icon_tex="multiplayer_portal.tex"},
    {name="beefalo", icon_atlas="images/scrapbook_icons1.xml", icon_tex="beefalo.tex"},
    {name="klaus_sack", icon_atlas="images/scrapbook_icons1.xml", icon_tex="klaus_sack.tex"},
    {name="walrus_camp", icon_atlas="images/scrapbook_icons3.xml", icon_tex="walrus_camp.tex"},
    {name="walrus", icon_atlas="images/scrapbook_icons3.xml", icon_tex="walrus.tex"},
    {name="wasphive", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wasphive.tex"},
    {name="lightninggoat", icon_atlas="images/scrapbook_icons1.xml", icon_tex="lightninggoat.tex"},
    {name="moose", icon_atlas="images/scrapbook_icons2.xml", icon_tex="moose.tex"},
    {name="deerclops", icon_atlas="images/scrapbook_icons1.xml", icon_tex="deerclops.tex"},
    {name="antlion", icon_atlas="images/scrapbook_icons1.xml", icon_tex="antlion.tex"},
    {name="bearger", icon_atlas="images/scrapbook_icons1.xml", icon_tex="bearger.tex"},
    {name="lava_pond", icon_atlas="images/scrapbook_icons1.xml", icon_tex="dragonfly.tex", is_single = true},
    {name="beequeenhive", icon_atlas="images/scrapbook_icons1.xml", icon_tex="beequeenhivegrown.tex"},
    {name="balatro_machine", icon_atlas="images/scrapbook_icons1.xml", icon_tex="balatro_machine.tex"},
    {name="oasislake", icon_atlas="images/scrapbook_icons2.xml", icon_tex="oasislake.tex"},
    {name="crabking", icon_atlas="images/scrapbook_icons1.xml", icon_tex="crabking.tex"},
    {name="moon_fissure", icon_atlas="images/scrapbook_icons2.xml", icon_tex="moon_fissure.tex"},
    {name="mermking", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mermking.tex"},
    {name="pigking", icon_atlas="images/scrapbook_icons2.xml", icon_tex="pigking.tex"},
    {name="hermitcrab", icon_atlas="images/scrapbook_icons1.xml", icon_tex="hermitcrab.tex"},
    {name="moonbase", icon_atlas="images/scrapbook_icons2.xml", icon_tex="moonbase.tex"},
    {name="chester_eyebone", icon_atlas="images/scrapbook_icons1.xml", icon_tex="chester.tex"},
    {name="hutch_fishbowl", icon_atlas="images/scrapbook_icons1.xml", icon_tex="hutch.tex"},
    {name="rock_moon_shell", icon_atlas="images/scrapbook_icons2.xml", icon_tex="rock_moon_shell.tex"},
    {name="dirtpile", icon_atlas="images/scrapbook_icons1.xml", icon_tex="dirtpile.tex"},
    {name="animal_track", icon_atlas="images/scrapbook_icons1.xml", icon_tex="animal_track.tex"},
    {name="koalefant_winter", icon_atlas="images/scrapbook_icons1.xml", icon_tex="koalefant_winter.tex"},
    {name="koalefant_summer", icon_atlas="images/scrapbook_icons1.xml", icon_tex="koalefant_summer.tex"},
    {name="spat", icon_atlas="images/scrapbook_icons3.xml", icon_tex="spat.tex"},
    {name="warg", icon_atlas="images/scrapbook_icons3.xml", icon_tex="warg.tex"},
    {name="atrium_gate", icon_atlas="images/scrapbook_icons1.xml", icon_tex="atrium_gate.tex"},
    {name="lureplant", icon_atlas="images/scrapbook_icons2.xml", icon_tex="lureplant.tex"},
    {name="tallbird", icon_atlas="images/scrapbook_icons3.xml", icon_tex="tallbird.tex"},
    {name="terrariumchest", icon_atlas="images/scrapbook_icons3.xml", icon_tex="terrariumchest.tex"},
    {name="terrarium", icon_atlas="images/inventoryimages3.xml", icon_tex="terrarium.tex", icon_size_x = 40, icon_size_y = 40},
    {name="terrarium_crimson", icon_atlas="images/inventoryimages3.xml", icon_tex="terrarium_crimson.tex", icon_size_x = 40, icon_size_y = 40},
    {name="terrarium_cooldown", icon_atlas="images/inventoryimages3.xml", icon_tex="terrarium_cooldown.tex", icon_size_x = 40, icon_size_y = 40},
    {name="watertree_pillar", icon_atlas="images/scrapbook_icons3.xml", icon_tex="watertree_pillar.tex"},
    {name="saltstack", icon_atlas="images/scrapbook_icons2.xml", icon_tex="saltstack.tex"},
    {name="minotaur", icon_atlas="images/scrapbook_icons2.xml", icon_tex="minotaur.tex"},
    {name="ancient_altar", icon_atlas="images/scrapbook_icons1.xml", icon_tex="ancient_altar.tex"},
    {name="ancient_altar_broken", icon_atlas="images/scrapbook_icons1.xml", icon_tex="ancient_altar_broken.tex"},
    {name="toadstool_cap", icon_atlas="images/scrapbook_icons3.xml", icon_tex="toadstool_cap.tex"},
    {name="monkeyqueen", icon_atlas="images/scrapbook_icons2.xml", icon_tex="monkeyqueen.tex"},
    {name="lunarthrall_plant", icon_atlas="images/scrapbook_icons2.xml", icon_tex="lunarthrall_plant.tex"},
    {name="lunarrift_portal", icon_atlas="images/scrapbook_icons2.xml", icon_tex="lunarrift_portal.tex"},
    {name="shadowrift_portal", icon_atlas="images/scrapbook_icons2.xml", icon_tex="shadowrift_portal.tex"},
    {name="malbatross", icon_atlas="images/scrapbook_icons2.xml", icon_tex="malbatross.tex"},
    {name="wagstaff_machinery", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wagstaff_machinery.tex"},
    {name="junk_pile_big", icon_atlas="images/scrapbook_icons1.xml", icon_tex="junk_pile_big.tex"},
    {name="daywalker", icon_atlas="images/scrapbook_icons1.xml", icon_tex="daywalker.tex"},
    {name="daywalker2", icon_atlas="images/scrapbook_icons1.xml", icon_tex="daywalker2.tex"},
    {name="wormlight_plant", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wormlight_plant.tex"},
    {name="wormlight", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wormlight.tex"},
    {name="worm", icon_atlas="images/scrapbook_icons3.xml", icon_tex="worm.tex"},
    {name="hotspring", icon_atlas="images/scrapbook_icons1.xml", icon_tex="hotspring.tex"},
    {name="deer", icon_atlas="images/scrapbook_icons1.xml", icon_tex="deer.tex"},
    {name="archive_cookpot", icon_atlas="images/scrapbook_icons1.xml", icon_tex="archive_cookpot.tex"},
    {name="archive_switch_base", icon_atlas="images/scrapbook_icons1.xml", icon_tex="archive_switch_base.tex"},
    {name="archive_portal", icon_atlas="images/scrapbook_icons1.xml", icon_tex="archive_portal.tex"},
    {name="archive_orchestrina_base", icon_atlas="images/scrapbook_icons1.xml", icon_tex="archive_orchestrina_main.tex"},
    {name="dustmoth", icon_atlas="images/scrapbook_icons1.xml", icon_tex="dustmoth.tex"},
    {name="bishop", icon_atlas="images/scrapbook_icons1.xml", icon_tex="bishop.tex"},
    {name="knight", icon_atlas="images/scrapbook_icons1.xml", icon_tex="knight.tex"},
    {name="rook", icon_atlas="images/scrapbook_icons2.xml", icon_tex="rook.tex"},
    {name="bishop_nightmare", icon_atlas="images/scrapbook_icons1.xml", icon_tex="bishop_nightmare.tex"},
    {name="knight_nightmare", icon_atlas="images/scrapbook_icons1.xml", icon_tex="knight_nightmare.tex"},
    {name="rook_nightmare", icon_atlas="images/scrapbook_icons2.xml", icon_tex="rook_nightmare.tex"},
    {name="wormhole", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wormhole.tex"},
    {name="cave_entrance", icon_atlas="images/scrapbook_icons1.xml", icon_tex="cave_entrance.tex"},
    {name="cave_exit", icon_atlas="images/scrapbook_icons1.xml", icon_tex="cave_exit.tex"},
    {name="critterlab", icon_atlas="images/scrapbook_icons1.xml", icon_tex="critterlab.tex"},
    {name="fruitdragon", icon_atlas="images/scrapbook_icons1.xml", icon_tex="fruitdragon.tex"},
    {name="leif", icon_atlas="images/scrapbook_icons1.xml", icon_tex="leif.tex"},
    {name="statueglommer", icon_atlas="images/scrapbook_icons3.xml", icon_tex="statueglommer.tex"},
    {name="glommer", icon_atlas="images/scrapbook_icons1.xml", icon_tex="glommer.tex"},
    {name="mole", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mole.tex"},
    {name="mandrake_planted", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mandrake_planted.tex"},
    {name="mushgnome", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mushgnome.tex"},
    {name="itemmimic_revealed", icon_atlas="images/scrapbook_icons1.xml", icon_tex="itemmimic_revealed.tex"},
    {name="pond", icon_atlas="images/scrapbook_icons2.xml", icon_tex="pond.tex"},
    {name="pirate_stash", icon_atlas="images/scrapbook_icons2.xml", icon_tex="pirate_stash.tex"},
    {name="icefishing_hole", icon_atlas="images/scrapbook_icons2.xml", icon_tex="sharkboi.tex"},
    {name="spiderqueen", icon_atlas="images/scrapbook_icons3.xml", icon_tex="spiderqueen.tex"},
    {name="spiderden", icon_atlas="images/scrapbook_icons3.xml", icon_tex="spiderden.tex"},
    {name="wagpunk_workstation", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wagpunk_workstation.tex"},
    {name="wanderingtrader", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wanderingtrader.tex"},
    {name="mound", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mound.tex"},
    {name="houndmound", icon_atlas="images/scrapbook_icons1.xml", icon_tex="houndmound.tex"},
    {name="resurrectionstone", icon_atlas="images/scrapbook_icons2.xml", icon_tex="resurrectionstone.tex"},
    {name="rock_avocado_bush", icon_atlas="images/scrapbook_icons2.xml", icon_tex="rock_avocado_bush.tex"},
    {name="mutateddeerclops", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mutateddeerclops.tex"},
    {name="mutatedbearger", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mutatedbearger.tex"},
    {name="mutatedwarg", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mutatedwarg.tex"},
    {name="otter", icon_atlas="images/scrapbook_icons2.xml", icon_tex="otter.tex"},
    {name="otterden", icon_atlas="images/scrapbook_icons2.xml", icon_tex="otterden.tex"},
    {name="catcoon", icon_atlas="images/scrapbook_icons1.xml", icon_tex="catcoon.tex"},
    {name="catcoonden", icon_atlas="images/scrapbook_icons1.xml", icon_tex="catcoonden.tex"},
    {name="pighouse", icon_atlas="images/scrapbook_icons2.xml", icon_tex="pighouse.tex"},
    {name="rabbithouse", icon_atlas="images/scrapbook_icons2.xml", icon_tex="rabbithouse.tex"},
    {name="mermhouse", icon_atlas="images/scrapbook_icons2.xml", icon_tex="mermhouse.tex"},
    {name="ruins_shadeling", icon_atlas="images/scrapbook_icons2.xml", icon_tex="ruins_shadeling.tex"},
    {name="livingtree", icon_atlas="images/scrapbook_icons2.xml", icon_tex="livingtree.tex"},
    {name="rocky", icon_atlas="images/scrapbook_icons2.xml", icon_tex="rocky.tex"},
    {name="spiderhole", icon_atlas="images/scrapbook_icons3.xml", icon_tex="spiderhole_rock.tex"},
    {name="stagehand", icon_atlas="images/scrapbook_icons3.xml", icon_tex="stagehand.tex"},
    {name="tentacle_pillar", icon_atlas="images/scrapbook_icons3.xml", icon_tex="tentacle_pillar.tex"},
    {name="tentacle_pillar_hole", icon_atlas="images/scrapbook_icons3.xml", icon_tex="tentacle_pillar_hole.tex"},
    {name="slurtlehole", icon_atlas="images/scrapbook_icons3.xml", icon_tex="slurtlehole.tex"},
    {name="skeleton", icon_atlas="images/scrapbook_icons3.xml", icon_tex="skeleton.tex"},
    {name="wagdrone_rolling", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wagdrone_rolling.tex"},
    {name="wagdrone_flying", icon_atlas="images/scrapbook_icons3.xml", icon_tex="wagdrone_flying.tex"},
    {name="storage_robot", icon_atlas="images/inventoryimages3.xml", icon_tex="storage_robot.tex", icon_size_x = 40, icon_size_y = 40},
    {name="wx78_scanner_item", icon_atlas="images/inventoryimages3.xml", icon_tex="wx78_scanner_item.tex", icon_size_x = 40, icon_size_y = 40},
    {name="atrium_key", icon_atlas="images/inventoryimages1.xml", icon_tex="atrium_key.tex", icon_size_x = 40, icon_size_y = 40},
    -- {name="fireflies", icon_atlas="images/inventoryimages2.xml", icon_tex="fireflies.tex", icon_size_x = 40, icon_size_y = 40},
    {name="sculpture_rookbody", icon_atlas="images/scrapbook_icons2.xml", icon_tex="sculpture_rookbody.tex"},
    {name="sculpture_bishophead", icon_atlas="images/inventoryimages3.xml", icon_tex="sculpture_bishophead.tex", icon_size_x = 40, icon_size_y = 40},
    {name="sculpture_knighthead", icon_atlas="images/inventoryimages3.xml", icon_tex="sculpture_knighthead.tex", icon_size_x = 40, icon_size_y = 40},
    {name="sculpture_rooknose", icon_atlas="images/inventoryimages3.xml", icon_tex="sculpture_rooknose.tex", icon_size_x = 40, icon_size_y = 40},
    {name="moon_altar_rock_idol", icon_atlas="images/scrapbook_icons2.xml", icon_tex="moon_altar_rock_idol.tex"},
    {name="moon_altar_rock_seed", icon_atlas="images/scrapbook_icons2.xml", icon_tex="moon_altar_rock_seed.tex"},
    {name="moon_altar_rock_glass", icon_atlas="images/scrapbook_icons2.xml", icon_tex="moon_altar_rock_glass.tex"},
    {name="moon_altar_crown", icon_atlas="images/inventoryimages2.xml", icon_tex="moon_altar_crown.tex", icon_size_x = 40, icon_size_y = 40},
    {name="moon_altar_ward", icon_atlas="images/inventoryimages2.xml", icon_tex="moon_altar_ward.tex", icon_size_x = 40, icon_size_y = 40},
    {name="moon_altar_icon", icon_atlas="images/inventoryimages2.xml", icon_tex="moon_altar_icon.tex", icon_size_x = 40, icon_size_y = 40},
    {name="moon_altar_seed", icon_atlas="images/inventoryimages2.xml", icon_tex="moon_altar_seed.tex", icon_size_x = 40, icon_size_y = 40},
    {name="moon_altar_glass", icon_atlas="images/inventoryimages2.xml", icon_tex="moon_altar_glass.tex", icon_size_x = 40, icon_size_y = 40},
    {name="moon_altar_idol", icon_atlas="images/inventoryimages2.xml", icon_tex="moon_altar_idol.tex", icon_size_x = 40, icon_size_y = 40},
    {name="messagebottle", icon_atlas="images/inventoryimages2.xml", icon_tex="messagebottle.tex", icon_size_x = 40, icon_size_y = 40},
    -- {name="driftwood_log", icon_atlas="images/inventoryimages1.xml", icon_tex="driftwood_log.tex", icon_size_x = 40, icon_size_y = 40},
}
